"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from plotly.colors import *

"""For a list of colors available in `plotly.express.colors`, please see

* the `tutorial on discrete color sequences <https://plotly.com/python/discrete-color/#color-sequences-in-plotly-express>`_
* the `list of built-in continuous color scales <https://plotly.com/python/builtin-colorscales/>`_
* the `tutorial on continuous colors <https://plotly.com/python/colorscales/>`_

Color scales are available within the following namespaces

* cyclical
* diverging
* qualitative
* sequential
"""
