"""
This type stub file was generated by pyright.
"""

class DataValidator(_plotly_utils.basevalidators.BaseDataValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


