"""
This type stub file was generated by pyright.
"""

import sys
from _plotly_utils.importers import relative_import

if sys.version_info < (3, 7):
    ...
else:
    ...
if sys.version_info < (3, 7):
    ...
else:
    orig_getattr = ...
    def __getattr__(import_name):
        ...
    
