"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from plotly import optional_imports
from ._imshow import imshow
from ._chart_types import area, bar, bar_polar, box, choropleth, choropleth_mapbox, density_contour, density_heatmap, density_mapbox, funnel, funnel_area, histogram, line, line_3d, line_geo, line_mapbox, line_polar, line_ternary, parallel_categories, parallel_coordinates, pie, scatter, scatter_3d, scatter_geo, scatter_mapbox, scatter_matrix, scatter_polar, scatter_ternary, strip, sunburst, timeline, treemap, violin
from ._core import NO_COLOR, defaults, get_trendline_results, set_mapbox_access_token
from ._special_inputs import Constant, IdentityMap, Range
from . import colors, data

"""
`plotly.express` is a terse, consistent, high-level wrapper around `plotly.graph_objects`
for rapid data exploration and figure generation. Learn more at https://plotly.express/
"""
pd = ...
if pd is None:
    ...
