"""
This type stub file was generated by pyright.
"""

def has_context(func):
    ...

class FalsyList(list):
    def __bool__(self):
        ...
    
    def __nonzero__(self):
        ...
    


falsy_triggered = ...
class CallbackContext:
    @property
    @has_context
    def inputs(self):
        ...
    
    @property
    @has_context
    def states(self):
        ...
    
    @property
    @has_context
    def triggered(self):
        ...
    
    @property
    @has_context
    def outputs_list(self):
        ...
    
    @property
    @has_context
    def inputs_list(self):
        ...
    
    @property
    @has_context
    def states_list(self):
        ...
    
    @property
    @has_context
    def response(self):
        ...
    
    @staticmethod
    @has_context
    def record_timing(name, duration=..., description=...):
        """Records timing information for a server resource.

        :param name: The name of the resource.
        :type name: string

        :param duration: The time in seconds to report. Internally, this
            is rounded to the nearest millisecond.
        :type duration: float or None

        :param description: A description of the resource.
        :type description: string or None
        """
        ...
    


callback_context = ...
