"""
This type stub file was generated by pyright.
"""

def load_dash_env_vars():
    ...

DASH_ENV_VARS = ...
def get_combined_config(name, val, default=...):
    """Consolidate the config with priority from high to low provided init
    value > OS environ > default."""
    ...

def pathname_configs(url_base_pathname=..., routes_pathname_prefix=..., requests_pathname_prefix=...):
    ...

