"""
This type stub file was generated by pyright.
"""

def validate_callback(output, inputs, state, extra_args, types):
    ...

def validate_callback_arg(arg):
    ...

def validate_id_dict(arg):
    ...

def validate_id_string(arg):
    ...

def validate_output_spec(output, output_spec, Output):
    """
    This validation is for security and internal debugging, not for users,
    so the messages are not intended to be clear.
    `output` comes from the callback definition, `output_spec` from the request.
    """
    ...

def validate_multi_return(outputs_list, output_value, callback_id):
    ...

def fail_callback_output(output_value, output):
    ...

def check_obsolete(kwargs):
    ...

def validate_js_path(registered_paths, package_name, path_in_package_dist):
    ...

def validate_index(name, checks, index):
    ...

def validate_layout_type(value):
    ...

def validate_layout(layout, layout_value):
    ...

