"""
This type stub file was generated by pyright.
"""

class _Wildcard:
    def __init__(self, name) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def to_json(self):
        ...
    


MATCH = ...
ALL = ...
ALLSMALLER = ...
class DashDependency:
    def __init__(self, component_id, component_property) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def component_id_str(self):
        ...
    
    def to_dict(self):
        ...
    
    def __eq__(self, other) -> bool:
        """
        We use "==" to denote two deps that refer to the same prop on
        the same component. In the case of wildcard deps, this means
        the same prop on *at least one* of the same components.
        """
        ...
    
    def __hash__(self) -> int:
        ...
    


class Output(DashDependency):
    """Output of a callback."""
    allowed_wildcards = ...


class Input(DashDependency):
    """Input of callback: trigger an update when it is updated."""
    allowed_wildcards = ...


class State(DashDependency):
    """Use the value of a State in a callback but don't trigger updates."""
    allowed_wildcards = ...


class ClientsideFunction:
    def __init__(self, namespace=..., function_name=...) -> None:
        ...
    
    def __repr__(self):
        ...
    


def extract_callback_args(args, kwargs, name, type_):
    """Extract arguments for callback from a name and type"""
    ...

def handle_callback_args(args, kwargs):
    """Split args into outputs, inputs and states"""
    ...

