"""
This type stub file was generated by pyright.
"""

class Resources:
    def __init__(self, resource_name) -> None:
        ...
    
    def append_resource(self, resource):
        ...
    
    def get_all_resources(self, dev_bundles=...):
        ...
    


class _Config:
    def __init__(self, serve_locally, eager_loading) -> None:
        ...
    


class Css:
    def __init__(self, serve_locally) -> None:
        ...
    
    def append_css(self, stylesheet):
        ...
    
    def get_all_css(self):
        ...
    


class Scripts:
    def __init__(self, serve_locally, eager) -> None:
        ...
    
    def append_script(self, script):
        ...
    
    def get_all_scripts(self, dev_bundles=...):
        ...
    


