"""
This type stub file was generated by pyright.
"""

class ColorwayValidator(_plotly_utils.basevalidators.ColorlistValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


