"""
This type stub file was generated by pyright.
"""

class HoverdistanceValidator(_plotly_utils.basevalidators.IntegerValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


