"""
This type stub file was generated by pyright.
"""

class OrientationValidator(_plotly_utils.basevalidators.AngleValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


