"""
This type stub file was generated by pyright.
"""

class Paper_BgcolorValidator(_plotly_utils.basevalidators.ColorValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


