"""
This type stub file was generated by pyright.
"""

class ShowscaleValidator(_plotly_utils.basevalidators.BooleanValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


