"""
This type stub file was generated by pyright.
"""

class TextValidator(_plotly_utils.basevalidators.DataArrayValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


