"""
This type stub file was generated by pyright.
"""

class XaxisValidator(_plotly_utils.basevalidators.SubplotidValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


