"""
This type stub file was generated by pyright.
"""

class YgapValidator(_plotly_utils.basevalidators.NumberValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


