"""
This type stub file was generated by pyright.
"""

class Yperiod0Validator(_plotly_utils.basevalidators.AnyValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


