"""
This type stub file was generated by pyright.
"""

class ZhoverformatValidator(_plotly_utils.basevalidators.StringValidator):
    def __init__(self, plotly_name=..., parent_name=..., **kwargs) -> None:
        ...
    


