"""
This type stub file was generated by pyright.
"""

import sys
from _plotly_utils.importers import relative_import
from plotly.io import templates

if sys.version_info < (3, 7):
    ...
else:
    ...
